from .inappropriate import register_inappropriate_handler
from .usual_commands import register_all_usual_command_handlers
from .adding_handlers import register_all_adding_handlers
from .editing_handlers import register_all_editing_handlers
from .base_handlers import register_all_base_handlers